# Generated by Django 4.2.11 on 2024-04-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_quantityofclothes_onesize_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantityofshoes',
            name='s28',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quantityofshoes',
            name='s29',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quantityofshoes',
            name='s30',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quantityofshoes',
            name='s31',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quantityofshoes',
            name='s32',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quantityofshoes',
            name='s33',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quantityofshoes',
            name='s34',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
