# Generated by Django 4.2.11 on 2024-04-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_quantityofshoes_s28_quantityofshoes_s29_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantityofclothes',
            name='XSS',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
